"""
Integration tests for search endpoints.

Tests the complete search functionality including caching, filtering,
and multi-strategy search with real database queries.
"""
import pytest
from httpx import AsyncClient
from sqlalchemy.ext.asyncio import AsyncSession

from src.db.models.gudid_device import GUDIDDevice
from src.db.models.organization import Organization
from src.db.models.vendor_device import VendorDevice
from src.services.search_service import search_service


class TestSearchEndpoints:
    """Integration tests for device search functionality."""
    
    @pytest.fixture
    async def setup_test_devices(self, db: AsyncSession):
        """Create test devices for search tests."""
        # Create organization
        org = Organization(
            name="Test Medical Center",
            type="hospital",
            subdomain="test-medical"
        )
        db.add(org)
        
        # Create GUDID devices
        gudid_devices = [
            GUDIDDevice(
                primary_di="12345678901234",
                device_name="Cardiac Pacemaker Model X",
                manufacturer_name="Medtronic",
                brand_name="Medtronic",
                model_number="PM-X100",
                device_class="III",
                device_class_name="Class III",
                gmdn_terms="Pacemaker, cardiac, implantable",
                mri_safety="MR Conditional",
                sterile=True,
                implantable=True,
                life_supporting=True,
                search_vector=None  # Would be generated by trigger
            ),
            GUDIDDevice(
                primary_di="98765432109876",
                device_name="Hip Implant Titanium",
                manufacturer_name="Johnson & Johnson",
                brand_name="DePuy Synthes",
                model_number="HIP-2000",
                device_class="II",
                device_class_name="Class II",
                gmdn_terms="Hip joint prosthesis",
                mri_safety="MR Safe",
                sterile=True,
                implantable=True,
                life_supporting=False,
                search_vector=None
            ),
            GUDIDDevice(
                primary_di="11111111111111",
                device_name="Surgical Scalpel",
                manufacturer_name="BD",
                brand_name="BD",
                model_number="SC-100",
                device_class="I",
                device_class_name="Class I",
                gmdn_terms="Scalpel, surgical",
                mri_safety="MR Safe",
                sterile=True,
                single_use=True,
                implantable=False,
                life_supporting=False,
                search_vector=None
            )
        ]
        db.add_all(gudid_devices)
        
        # Create vendor devices
        vendor_devices = [
            VendorDevice(
                gudid_device_di="12345678901234",
                organization_id=org.id,
                internal_sku="MED-PM-001",
                custom_name="Premium Cardiac Pacemaker",
                list_price=25000.00,
                access_level="public",
                is_active=True
            ),
            VendorDevice(
                gudid_device_di="98765432109876",
                organization_id=org.id,
                internal_sku="JJ-HIP-001",
                custom_name="Titanium Hip Replacement System",
                list_price=15000.00,
                access_level="public",
                is_active=True
            )
        ]
        db.add_all(vendor_devices)
        
        await db.commit()
        
        return {
            "organization": org,
            "gudid_devices": gudid_devices,
            "vendor_devices": vendor_devices
        }
    
    @pytest.mark.asyncio
    async def test_search_devices_basic(
        self, 
        client: AsyncClient, 
        auth_headers: dict,
        setup_test_devices
    ):
        """Test basic device search functionality."""
        response = await client.post(
            "/api/v1/devices/search",
            headers=auth_headers,
            json={
                "query": "pacemaker",
                "page": 1,
                "limit": 10
            }
        )
        
        assert response.status_code == 200
        data = response.json()
        
        # Verify response structure
        assert "results" in data
        assert "total" in data
        assert "execution_time_ms" in data
        
        # Verify results
        assert data["total"] >= 1
        assert len(data["results"]) >= 1
        
        # Check first result
        first_result = data["results"][0]
        assert "device" in first_result
        assert "relevance_score" in first_result
        assert "pacemaker" in first_result["device"]["device_name"].lower()
    
    @pytest.mark.asyncio
    async def test_search_by_exact_di(
        self,
        client: AsyncClient,
        auth_headers: dict,
        setup_test_devices
    ):
        """Test exact Device Identifier search."""
        response = await client.post(
            "/api/v1/devices/search",
            headers=auth_headers,
            json={
                "query": "12345678901234",
                "page": 1,
                "limit": 10
            }
        )
        
        assert response.status_code == 200
        data = response.json()
        
        assert data["total"] == 1
        assert len(data["results"]) == 1
        
        device = data["results"][0]["device"]
        assert device["gudid_device"]["primary_di"] == "12345678901234"
        assert data["results"][0]["relevance_score"] == 1.0  # Exact match
    
    @pytest.mark.asyncio
    async def test_search_with_filters(
        self,
        client: AsyncClient,
        auth_headers: dict,
        setup_test_devices
    ):
        """Test search with filters applied."""
        response = await client.post(
            "/api/v1/devices/search",
            headers=auth_headers,
            json={
                "query": "implant",
                "filters": {
                    "device_class": ["II", "III"],
                    "sterile": True
                },
                "page": 1,
                "limit": 10
            }
        )
        
        assert response.status_code == 200
        data = response.json()
        
        # Should find both pacemaker and hip implant
        assert data["total"] >= 2
        
        # Verify all results match filters
        for result in data["results"]:
            device = result["device"]["gudid_device"]
            assert device["device_class"] in ["II", "III"]
            assert device["sterile"] is True
    
    @pytest.mark.asyncio
    async def test_search_manufacturer_filter(
        self,
        client: AsyncClient,
        auth_headers: dict,
        setup_test_devices
    ):
        """Test search with manufacturer filter."""
        response = await client.post(
            "/api/v1/devices/search",
            headers=auth_headers,
            json={
                "query": "",  # Empty query to get all
                "filters": {
                    "manufacturer": ["Medtronic"]
                },
                "page": 1,
                "limit": 10
            }
        )
        
        assert response.status_code == 200
        data = response.json()
        
        # Should only find Medtronic devices
        assert data["total"] >= 1
        
        for result in data["results"]:
            device = result["device"]["gudid_device"]
            assert device["manufacturer_name"] == "Medtronic"
    
    @pytest.mark.asyncio
    async def test_search_pagination(
        self,
        client: AsyncClient,
        auth_headers: dict,
        setup_test_devices
    ):
        """Test search pagination."""
        # First page
        response1 = await client.post(
            "/api/v1/devices/search",
            headers=auth_headers,
            json={
                "query": "",
                "page": 1,
                "limit": 2
            }
        )
        
        assert response1.status_code == 200
        data1 = response1.json()
        assert len(data1["results"]) <= 2
        
        # Second page
        response2 = await client.post(
            "/api/v1/devices/search",
            headers=auth_headers,
            json={
                "query": "",
                "page": 2,
                "limit": 2
            }
        )
        
        assert response2.status_code == 200
        data2 = response2.json()
        
        # Ensure different results
        if data2["results"]:
            page1_ids = {r["device"]["id"] for r in data1["results"]}
            page2_ids = {r["device"]["id"] for r in data2["results"]}
            assert page1_ids.isdisjoint(page2_ids)
    
    @pytest.mark.asyncio
    async def test_search_sorting(
        self,
        client: AsyncClient,
        auth_headers: dict,
        setup_test_devices
    ):
        """Test search result sorting options."""
        # Sort by name
        response = await client.post(
            "/api/v1/devices/search",
            headers=auth_headers,
            json={
                "query": "",
                "sort": "name",
                "page": 1,
                "limit": 10
            }
        )
        
        assert response.status_code == 200
        data = response.json()
        
        # Verify alphabetical order
        if len(data["results"]) > 1:
            names = [r["device"]["device_name"] for r in data["results"]]
            assert names == sorted(names)
    
    @pytest.mark.asyncio
    async def test_search_access_control(
        self,
        client: AsyncClient,
        db: AsyncSession,
        setup_test_devices
    ):
        """Test search respects access control."""
        # Create private device
        private_device = VendorDevice(
            gudid_device_di="11111111111111",
            organization_id=setup_test_devices["organization"].id,
            internal_sku="PRIVATE-001",
            custom_name="Private Device",
            access_level="private",
            is_active=True
        )
        db.add(private_device)
        await db.commit()
        
        # Create user from different org
        other_org = Organization(
            name="Other Hospital",
            type="hospital",
            subdomain="other"
        )
        db.add(other_org)
        await db.commit()
        
        # Search as user from different org
        # Should not see private device
        # (This would need proper auth setup for different user)
    
    @pytest.mark.asyncio
    async def test_search_caching(
        self,
        client: AsyncClient,
        auth_headers: dict,
        setup_test_devices
    ):
        """Test search results are cached."""
        # First request
        response1 = await client.post(
            "/api/v1/devices/search",
            headers=auth_headers,
            json={
                "query": "pacemaker",
                "page": 1,
                "limit": 10
            }
        )
        
        assert response1.status_code == 200
        data1 = response1.json()
        time1 = data1["execution_time_ms"]
        
        # Second identical request (should be cached)
        response2 = await client.post(
            "/api/v1/devices/search",
            headers=auth_headers,
            json={
                "query": "pacemaker",
                "page": 1,
                "limit": 10
            }
        )
        
        assert response2.status_code == 200
        data2 = response2.json()
        
        # Cached response should be faster
        assert data2.get("from_cache") is True
        assert data2["execution_time_ms"] < time1
    
    @pytest.mark.asyncio
    async def test_search_empty_query(
        self,
        client: AsyncClient,
        auth_headers: dict
    ):
        """Test search with empty query returns error."""
        response = await client.post(
            "/api/v1/devices/search",
            headers=auth_headers,
            json={
                "query": "",
                "page": 1,
                "limit": 10
            }
        )
        
        # Should return empty results or error
        assert response.status_code in [200, 400]
        if response.status_code == 200:
            data = response.json()
            assert data["total"] == 0
            assert data["results"] == []
    
    @pytest.mark.asyncio
    async def test_search_special_characters(
        self,
        client: AsyncClient,
        auth_headers: dict,
        setup_test_devices
    ):
        """Test search handles special characters properly."""
        # Search with special characters
        response = await client.post(
            "/api/v1/devices/search",
            headers=auth_headers,
            json={
                "query": "PM-X100",  # Model number with hyphen
                "page": 1,
                "limit": 10
            }
        )
        
        assert response.status_code == 200
        data = response.json()
        
        # Should find the pacemaker by model number
        assert data["total"] >= 1
        found = False
        for result in data["results"]:
            if result["device"]["gudid_device"]["model_number"] == "PM-X100":
                found = True
                break
        assert found
    
    @pytest.mark.asyncio
    async def test_search_performance(
        self,
        client: AsyncClient,
        auth_headers: dict,
        setup_test_devices
    ):
        """Test search performance meets SLA."""
        response = await client.post(
            "/api/v1/devices/search",
            headers=auth_headers,
            json={
                "query": "device",
                "page": 1,
                "limit": 50
            }
        )
        
        assert response.status_code == 200
        data = response.json()
        
        # Should complete within 200ms as per SLA
        assert data["execution_time_ms"] < 200
    
    @pytest.mark.asyncio
    async def test_search_facets(
        self,
        client: AsyncClient,
        auth_headers: dict,
        setup_test_devices
    ):
        """Test search returns facets for filtering."""
        response = await client.post(
            "/api/v1/devices/search",
            headers=auth_headers,
            json={
                "query": "implant",
                "page": 1,
                "limit": 10
            }
        )
        
        assert response.status_code == 200
        data = response.json()
        
        # Should include facets
        assert "facets" in data
        # TODO: Implement facets in search endpoint
        
    @pytest.mark.asyncio
    async def test_search_suggestions(
        self,
        client: AsyncClient,
        auth_headers: dict,
        setup_test_devices
    ):
        """Test search provides suggestions for typos."""
        # Search with typo
        response = await client.post(
            "/api/v1/devices/search",
            headers=auth_headers,
            json={
                "query": "pacemker",  # Typo in pacemaker
                "page": 1,
                "limit": 10
            }
        )
        
        assert response.status_code == 200
        data = response.json()
        
        # Should include suggestions
        assert "suggestions" in data
        # TODO: Implement suggestions based on search history
