"""
Integration tests for Performance & Load Testing.
Tests cover performance benchmarks, scalability, and stress testing.
"""

import pytest
from httpx import AsyncClient
from sqlalchemy.ext.asyncio import AsyncSession
from datetime import datetime, timedelta
import asyncio
import time
import statistics
from typing import List, Dict, Tuple
from concurrent.futures import ThreadPoolExecutor
import psutil
import gc

from src.db.models.user import User
from src.db.models.organization import Organization
from src.db.models.gudid_device import GUDIDDevice
from src.db.models.vendor_device import VendorDevice
from src.db.models.analytics_event import AnalyticsEvent
from src.db.models.chat import ChatConversation
from src.db.models.device_document import DeviceDocument
from src.services.auth_service import AuthService


class TestPerformanceLoad:
    """Test cases for Performance & Load Testing - Section 14"""

    @pytest.fixture(scope="class")
    async def setup_large_dataset(self, db: AsyncSession):
        """Create large dataset for performance testing"""
        # Note: In real testing, this would be 4.8M devices
        # For integration tests, we'll use a smaller representative set
        
        # Create test organization
        org = Organization(
            name="Performance Test Hospital",
            type="hospital",
            subdomain="perf-test",
            license_tier="enterprise"
        )
        db.add(org)
        await db.flush()
        
        auth_service = AuthService()
        
        # Create test users
        users = []
        for i in range(100):  # 100 test users
            user = User(
                email=f"user{i}@perftest.com",
                password_hash=auth_service.get_password_hash("password123"),
                first_name=f"User{i}",
                last_name="PerfTest",
                role="nurse" if i % 3 == 0 else "physician",
                organization_id=org.id
            )
            users.append(user)
        
        db.add_all(users)
        await db.flush()
        
        # Create devices (simulating FDA dataset)
        devices = []
        batch_size = 1000
        device_count = 10000  # Reduced for testing, would be 4.8M in production
        
        for batch_start in range(0, device_count, batch_size):
            batch_devices = []
            for i in range(batch_start, min(batch_start + batch_size, device_count)):
                device = GUDIDDevice(
                    primary_di=f"00889842{i:06d}",
                    device_name=f"Test Device {i}",
                    manufacturer_name=f"Manufacturer {i % 100}",
                    device_class=["I", "II", "III"][i % 3],
                    device_description=f"Description for device {i} with searchable terms like infusion pump catheter monitor",
                    gmdn_terms=f"Term{i % 50}",
                    mri_safety=["Safe", "Conditional", "Unsafe"][i % 3],
                    sterile=i % 2 == 0,
                    single_use=i % 3 == 0,
                    search_vector=None  # Would be generated by trigger
                )
                batch_devices.append(device)
            
            db.add_all(batch_devices)
            devices.extend(batch_devices)
            
            # Commit in batches to avoid memory issues
            if len(batch_devices) == batch_size:
                await db.commit()
        
        await db.commit()
        
        # Create search indices (simulated)
        # In production, this would be Elasticsearch indexing
        
        return {
            "organization": org,
            "users": users,
            "devices": devices,
            "device_count": device_count
        }

    @pytest.fixture
    async def auth_tokens(self, client: AsyncClient, setup_large_dataset) -> List[str]:
        """Get auth tokens for multiple users"""
        users = setup_large_dataset["users"]
        tokens = []
        
        # Get tokens for first 10 users
        for user in users[:10]:
            response = await client.post(
                "/api/v1/auth/login",
                data={"username": user.email, "password": "password123"}
            )
            tokens.append(response.json()["access_token"])
        
        return tokens

    @pytest.mark.asyncio
    async def test_api_response_time_benchmarks(
        self, client: AsyncClient, db: AsyncSession, auth_tokens
    ):
        """Test API response time requirements"""
        token = auth_tokens[0]
        headers = {"Authorization": f"Bearer {token}"}
        
        # Define endpoints and their SLA
        endpoints_sla = [
            ("/api/v1/auth/verify", "GET", 100),  # <100ms
            ("/api/v1/devices/search", "POST", 200),  # <200ms  
            ("/api/v1/documents/upload/presigned", "POST", 500),  # <500ms
            ("/api/v1/analytics/summary", "GET", 1000),  # <1s
        ]
        
        results = {}
        
        for endpoint, method, sla_ms in endpoints_sla:
            times = []
            
            # Run multiple requests to get average
            for _ in range(10):
                start = time.time()
                
                if method == "GET":
                    response = await client.get(endpoint, headers=headers)
                elif method == "POST":
                    if "search" in endpoint:
                        response = await client.post(
                            endpoint,
                            json={"query": "infusion pump"},
                            headers=headers
                        )
                    else:
                        response = await client.post(endpoint, headers=headers)
                
                elapsed = (time.time() - start) * 1000  # Convert to ms
                times.append(elapsed)
                
                # Request should succeed
                assert response.status_code in [200, 201, 400]  # 400 for missing data
            
            # Calculate percentiles
            times.sort()
            p50 = statistics.median(times)
            p95 = times[int(len(times) * 0.95)]
            p99 = times[int(len(times) * 0.99)] if len(times) > 99 else times[-1]
            
            results[endpoint] = {
                "p50": p50,
                "p95": p95,
                "p99": p99,
                "sla_ms": sla_ms,
                "passed": p95 < sla_ms
            }
            
            # Assert 95th percentile meets SLA
            assert p95 < sla_ms, f"{endpoint} p95 {p95:.2f}ms exceeds SLA {sla_ms}ms"
        
        # Print results for analysis
        for endpoint, metrics in results.items():
            print(f"\n{endpoint}:")
            print(f"  P50: {metrics['p50']:.2f}ms")
            print(f"  P95: {metrics['p95']:.2f}ms") 
            print(f"  P99: {metrics['p99']:.2f}ms")
            print(f"  SLA: {metrics['sla_ms']}ms - {'PASS' if metrics['passed'] else 'FAIL'}")

    @pytest.mark.asyncio
    async def test_device_search_performance(
        self, client: AsyncClient, db: AsyncSession, auth_tokens, setup_large_dataset
    ):
        """Test device search performance with 10K+ devices"""
        token = auth_tokens[0]
        headers = {"Authorization": f"Bearer {token}"}
        
        device_count = setup_large_dataset["device_count"]
        
        # Different search scenarios
        search_queries = [
            {"query": "pump"},  # Common term
            {"query": "infusion pump", "filters": {"device_class": ["II", "III"]}},  # With filters
            {"query": "manufact", "fuzzy": True},  # Fuzzy search
            {"query": "00889842000001"},  # Exact DI search
            {"query": "MRI safe catheter"},  # Multi-term
            {"query": "nonexistentdevice12345"},  # No results
        ]
        
        for search in search_queries:
            times = []
            
            for _ in range(5):
                start = time.time()
                response = await client.post(
                    "/api/v1/devices/search",
                    json=search,
                    headers=headers
                )
                elapsed = (time.time() - start) * 1000
                times.append(elapsed)
                
                assert response.status_code == 200
                
                # Verify results
                data = response.json()
                assert "results" in data
                assert "total_count" in data
                assert "execution_time_ms" in data
            
            avg_time = statistics.mean(times)
            assert avg_time < 200, f"Search '{search['query']}' avg {avg_time:.2f}ms exceeds 200ms"

    @pytest.mark.asyncio
    async def test_concurrent_user_load(
        self, client: AsyncClient, db: AsyncSession, auth_tokens
    ):
        """Test system with concurrent users"""
        # Simulate 100 concurrent users (reduced from 10K for testing)
        concurrent_users = 100
        requests_per_user = 10
        
        async def user_session(token: str, user_id: int):
            """Simulate a user session"""
            headers = {"Authorization": f"Bearer {token}"}
            results = []
            
            for i in range(requests_per_user):
                # Mix of different operations
                operation = i % 5
                start = time.time()
                
                try:
                    if operation == 0:  # Search
                        response = await client.post(
                            "/api/v1/devices/search",
                            json={"query": f"device {user_id}"},
                            headers=headers
                        )
                    elif operation == 1:  # View device
                        response = await client.get(
                            f"/api/v1/devices/00889842{user_id:06d}",
                            headers=headers
                        )
                    elif operation == 2:  # Analytics
                        response = await client.get(
                            "/api/v1/analytics/summary",
                            headers=headers
                        )
                    elif operation == 3:  # Create note
                        response = await client.post(
                            "/api/v1/notes",
                            json={"content": f"Note from user {user_id}"},
                            headers=headers
                        )
                    else:  # List documents
                        response = await client.get(
                            "/api/v1/documents",
                            headers=headers
                        )
                    
                    elapsed = time.time() - start
                    results.append({
                        "operation": operation,
                        "status": response.status_code,
                        "time": elapsed,
                        "success": 200 <= response.status_code < 300
                    })
                    
                except Exception as e:
                    results.append({
                        "operation": operation,
                        "status": 0,
                        "time": time.time() - start,
                        "success": False,
                        "error": str(e)
                    })
                
                # Small delay between requests
                await asyncio.sleep(0.1)
            
            return results
        
        # Create tasks for concurrent users
        tasks = []
        for i in range(concurrent_users):
            token = auth_tokens[i % len(auth_tokens)]
            task = user_session(token, i)
            tasks.append(task)
        
        # Execute concurrently
        start_time = time.time()
        all_results = await asyncio.gather(*tasks)
        total_time = time.time() - start_time
        
        # Analyze results
        total_requests = 0
        successful_requests = 0
        response_times = []
        
        for user_results in all_results:
            for result in user_results:
                total_requests += 1
                if result["success"]:
                    successful_requests += 1
                    response_times.append(result["time"])
        
        success_rate = (successful_requests / total_requests) * 100
        avg_response_time = statistics.mean(response_times) if response_times else 0
        
        # Assertions
        assert success_rate > 99, f"Success rate {success_rate:.2f}% below 99%"
        assert avg_response_time < 1.0, f"Avg response time {avg_response_time:.2f}s exceeds 1s"
        
        # Calculate throughput
        throughput = total_requests / total_time
        print(f"\nConcurrent Load Test Results:")
        print(f"  Total requests: {total_requests}")
        print(f"  Success rate: {success_rate:.2f}%")
        print(f"  Avg response time: {avg_response_time:.3f}s")
        print(f"  Throughput: {throughput:.2f} req/s")

    @pytest.mark.asyncio
    async def test_websocket_connections(
        self, client: AsyncClient, db: AsyncSession, auth_tokens
    ):
        """Test WebSocket connection scalability"""
        # Test with multiple WebSocket connections
        websocket_count = 100  # Reduced from 5000 for testing
        
        async def websocket_client(token: str, client_id: int):
            """Simulate WebSocket client"""
            # In real implementation, would use websocket connection
            # For testing, simulate with regular HTTP calls
            headers = {"Authorization": f"Bearer {token}"}
            
            # Simulate connection
            response = await client.post(
                "/api/v1/ws/connect",
                headers=headers
            )
            
            if response.status_code != 200:
                return {"client_id": client_id, "connected": False}
            
            # Simulate some messages
            messages_sent = 0
            for _ in range(5):
                response = await client.post(
                    "/api/v1/ws/message",
                    json={"type": "ping", "data": {"client_id": client_id}},
                    headers=headers
                )
                if response.status_code == 200:
                    messages_sent += 1
                
                await asyncio.sleep(0.5)
            
            return {
                "client_id": client_id,
                "connected": True,
                "messages_sent": messages_sent
            }
        
        # Create concurrent WebSocket connections
        tasks = []
        for i in range(websocket_count):
            token = auth_tokens[i % len(auth_tokens)]
            task = websocket_client(token, i)
            tasks.append(task)
        
        # Connect all clients
        results = await asyncio.gather(*tasks)
        
        # Analyze results
        connected_count = sum(1 for r in results if r.get("connected", False))
        connection_rate = (connected_count / websocket_count) * 100
        
        print(f"\nWebSocket Test Results:")
        print(f"  Attempted connections: {websocket_count}")
        print(f"  Successful connections: {connected_count}")
        print(f"  Connection rate: {connection_rate:.2f}%")
        
        # Should handle at least 100 concurrent connections
        assert connected_count >= 95, f"Only {connected_count} WebSocket connections established"

    @pytest.mark.asyncio
    async def test_database_connection_pool(
        self, client: AsyncClient, db: AsyncSession, auth_tokens
    ):
        """Test database connection pool under load"""
        # Monitor database connections during load
        initial_connections = await self._get_db_connection_count(db)
        
        # Generate database-heavy load
        async def db_heavy_operation(token: str):
            headers = {"Authorization": f"Bearer {token}"}
            
            # Operations that require database access
            operations = [
                client.get("/api/v1/users/me", headers=headers),
                client.get("/api/v1/devices?limit=100", headers=headers),
                client.get("/api/v1/analytics/events?limit=1000", headers=headers),
                client.post("/api/v1/audit-logs/search", json={"limit": 100}, headers=headers)
            ]
            
            results = await asyncio.gather(*operations, return_exceptions=True)
            return results
        
        # Run concurrent database operations
        tasks = []
        for i in range(50):  # 50 concurrent operations
            token = auth_tokens[i % len(auth_tokens)]
            task = db_heavy_operation(token)
            tasks.append(task)
        
        results = await asyncio.gather(*tasks)
        
        # Check connection pool metrics
        peak_connections = await self._get_db_connection_count(db)
        
        # Verify connection pool is working (not creating unlimited connections)
        assert peak_connections < 100, f"Too many database connections: {peak_connections}"
        
        # Verify no connection pool exhaustion errors
        errors = [r for r in results if isinstance(r, Exception)]
        connection_errors = [e for e in errors if "connection" in str(e).lower()]
        assert len(connection_errors) == 0, f"Connection pool errors: {connection_errors}"

    @pytest.mark.asyncio
    async def test_cache_performance(
        self, client: AsyncClient, db: AsyncSession, auth_tokens
    ):
        """Test cache hit rates and performance impact"""
        token = auth_tokens[0]
        headers = {"Authorization": f"Bearer {token}"}
        
        # First, make requests to populate cache
        cache_warming_queries = [
            "infusion pump",
            "catheter",
            "monitor",
            "MRI safe"
        ]
        
        for query in cache_warming_queries:
            await client.post(
                "/api/v1/devices/search",
                json={"query": query},
                headers=headers
            )
        
        # Now test cache performance
        cache_hit_times = []
        cache_miss_times = []
        
        # Cache hits (repeat previous queries)
        for query in cache_warming_queries:
            start = time.time()
            response = await client.post(
                "/api/v1/devices/search",
                json={"query": query},
                headers=headers
            )
            elapsed = time.time() - start
            cache_hit_times.append(elapsed)
            assert response.status_code == 200
        
        # Cache misses (new queries)
        for i in range(len(cache_warming_queries)):
            query = f"unique uncached query {i} {time.time()}"
            start = time.time()
            response = await client.post(
                "/api/v1/devices/search",
                json={"query": query},
                headers=headers
            )
            elapsed = time.time() - start
            cache_miss_times.append(elapsed)
            assert response.status_code == 200
        
        # Cache hits should be significantly faster
        avg_cache_hit = statistics.mean(cache_hit_times)
        avg_cache_miss = statistics.mean(cache_miss_times)
        
        print(f"\nCache Performance:")
        print(f"  Avg cache hit time: {avg_cache_hit*1000:.2f}ms")
        print(f"  Avg cache miss time: {avg_cache_miss*1000:.2f}ms")
        print(f"  Performance improvement: {((avg_cache_miss - avg_cache_hit) / avg_cache_miss * 100):.1f}%")
        
        # Cache hits should be at least 50% faster
        assert avg_cache_hit < avg_cache_miss * 0.5

    @pytest.mark.asyncio
    async def test_stress_test_endpoints(
        self, client: AsyncClient, db: AsyncSession, auth_tokens
    ):
        """Stress test critical endpoints"""
        # Test endpoints under extreme load
        token = auth_tokens[0]
        headers = {"Authorization": f"Bearer {token}"}
        
        # Image upload stress test
        async def stress_image_upload():
            # Create a fake image data (1MB)
            image_data = b"fake_image_data" * (1024 * 64)  # ~1MB
            
            start = time.time()
            response = await client.post(
                "/api/v1/images/recognize",
                files={"image": ("test.jpg", image_data, "image/jpeg")},
                headers=headers
            )
            elapsed = time.time() - start
            
            return {
                "status": response.status_code,
                "time": elapsed,
                "success": response.status_code in [200, 201, 413]  # 413 for size limit
            }
        
        # Run concurrent image uploads
        upload_tasks = [stress_image_upload() for _ in range(20)]
        upload_results = await asyncio.gather(*upload_tasks)
        
        successful_uploads = sum(1 for r in upload_results if r["success"])
        avg_upload_time = statistics.mean([r["time"] for r in upload_results])
        
        print(f"\nImage Upload Stress Test:")
        print(f"  Successful uploads: {successful_uploads}/20")
        print(f"  Avg upload time: {avg_upload_time:.2f}s")
        
        # At least 90% should succeed
        assert successful_uploads >= 18

    @pytest.mark.asyncio
    async def test_memory_usage_under_load(
        self, client: AsyncClient, db: AsyncSession, auth_tokens
    ):
        """Test memory usage doesn't grow unbounded"""
        # Get initial memory usage
        process = psutil.Process()
        initial_memory = process.memory_info().rss / 1024 / 1024  # MB
        
        # Generate load that could cause memory leaks
        async def memory_intensive_operation(token: str):
            headers = {"Authorization": f"Bearer {token}"}
            
            # Large data operations
            tasks = []
            
            # 1. Large search result
            tasks.append(client.post(
                "/api/v1/devices/search",
                json={"query": "*", "limit": 1000},
                headers=headers
            ))
            
            # 2. Large analytics query
            tasks.append(client.get(
                "/api/v1/analytics/events?limit=5000",
                headers=headers
            ))
            
            # 3. Bulk operation
            tasks.append(client.post(
                "/api/v1/devices/bulk-export",
                json={"format": "csv", "limit": 1000},
                headers=headers
            ))
            
            await asyncio.gather(*tasks, return_exceptions=True)
        
        # Run operations
        for i in range(10):
            tasks = []
            for j in range(5):
                token = auth_tokens[j % len(auth_tokens)]
                task = memory_intensive_operation(token)
                tasks.append(task)
            
            await asyncio.gather(*tasks)
            
            # Force garbage collection
            gc.collect()
            
            # Check memory after each iteration
            current_memory = process.memory_info().rss / 1024 / 1024
            memory_growth = current_memory - initial_memory
            
            print(f"Iteration {i+1}: Memory growth: {memory_growth:.2f}MB")
        
        # Final memory check
        final_memory = process.memory_info().rss / 1024 / 1024
        total_growth = final_memory - initial_memory
        
        print(f"\nMemory Usage Test:")
        print(f"  Initial memory: {initial_memory:.2f}MB")
        print(f"  Final memory: {final_memory:.2f}MB")
        print(f"  Total growth: {total_growth:.2f}MB")
        
        # Memory growth should be reasonable (< 500MB for this test)
        assert total_growth < 500, f"Excessive memory growth: {total_growth:.2f}MB"

    @pytest.mark.asyncio
    async def test_graceful_degradation(
        self, client: AsyncClient, db: AsyncSession, auth_tokens
    ):
        """Test system behavior under degraded conditions"""
        token = auth_tokens[0]
        headers = {"Authorization": f"Bearer {token}"}
        
        # Test with various failure scenarios
        # 1. Slow database queries (simulated)
        with patch("src.db.session.AsyncSession.execute") as mock_execute:
            # Make execute slow
            async def slow_execute(*args, **kwargs):
                await asyncio.sleep(2)  # 2 second delay
                # Return mock result
                from unittest.mock import MagicMock
                result = MagicMock()
                result.scalar_one_or_none.return_value = None
                result.scalars.return_value.all.return_value = []
                return result
            
            mock_execute.side_effect = slow_execute
            
            # System should timeout gracefully
            start = time.time()
            response = await client.get(
                "/api/v1/devices",
                headers=headers
            )
            elapsed = time.time() - start
            
            # Should timeout or return gracefully
            assert elapsed < 5, "Request didn't timeout appropriately"
            assert response.status_code in [200, 504]  # OK or Gateway Timeout

    @pytest.mark.asyncio
    async def test_request_rate_limiting(
        self, client: AsyncClient, db: AsyncSession, auth_tokens
    ):
        """Test rate limiting under load"""
        token = auth_tokens[0]
        headers = {"Authorization": f"Bearer {token}"}
        
        # Make requests up to and beyond rate limit
        rate_limit_per_hour = 1000
        burst_size = 50
        
        responses = []
        
        # Burst requests
        for i in range(burst_size + 10):
            response = await client.get(
                "/api/v1/devices",
                headers=headers
            )
            responses.append(response.status_code)
            
            # Small delay to avoid overwhelming
            if i % 10 == 0:
                await asyncio.sleep(0.1)
        
        # Should see rate limiting kick in
        limited_responses = [s for s in responses if s == 429]
        
        # Some requests should be rate limited
        assert len(limited_responses) > 0, "Rate limiting not working"
        
        # But not all requests (burst should be allowed)
        assert len(limited_responses) < len(responses), "All requests rate limited"

    async def _get_db_connection_count(self, db: AsyncSession) -> int:
        """Helper to get current database connection count"""
        result = await db.execute(
            "SELECT count(*) FROM pg_stat_activity WHERE datname = current_database()"
        )
        count = result.scalar()
        return count

    @pytest.mark.asyncio
    async def test_performance_metrics_collection(
        self, client: AsyncClient, db: AsyncSession, auth_tokens
    ):
        """Test that performance metrics are being collected"""
        token = auth_tokens[0]
        headers = {"Authorization": f"Bearer {token}"}
        
        # Make various requests
        endpoints = [
            ("/api/v1/devices", "GET"),
            ("/api/v1/devices/search", "POST"),
            ("/api/v1/analytics/summary", "GET")
        ]
        
        for endpoint, method in endpoints:
            if method == "GET":
                await client.get(endpoint, headers=headers)
            else:
                await client.post(
                    endpoint,
                    json={"query": "test"},
                    headers=headers
                )
        
        # Check metrics endpoint
        response = await client.get(
            "/api/v1/metrics/performance",
            headers=headers
        )
        
        if response.status_code == 200:
            metrics = response.json()
            
            # Verify metrics are collected
            assert "endpoints" in metrics
            assert len(metrics["endpoints"]) > 0
            
            # Check metric details
            for endpoint_metrics in metrics["endpoints"].values():
                assert "count" in endpoint_metrics
                assert "avg_response_time" in endpoint_metrics
                assert "p95_response_time" in endpoint_metrics
